name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
    - run: go version

    - name: Set up Task
      uses: arduino/setup-task@v1

    - name: Run docker compose
      run: task up

    - name: Test
      run: task test
