version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=esja
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
